### ISSUE TITLE
AttributeError: module 'trytond.model.fields' has no attribute 'Property'

### ISSUE THREAD

**Issue by emondi** [tryton-ar/sale_pos_ar#5]
Probando tryton 4.6 en debian testing, al instalar sale_pos_ar me tira el siguiente error:

```
Traceback (most recent call last):
  File "/usr/bin/trytond", line 29, in <module>
    Pool.start()
  File "/usr/lib/python3/dist-packages/trytond/pool.py", line 95, in start                                                                 
    register_classes()
  File "/usr/lib/python3/dist-packages/trytond/modules/__init__.py", line 373, in register_classes                                         
    mod_file, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module                                                                  
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                             
  File "/usr/lib/python3/dist-packages/trytond/modules/sale_pos_ar/__init__.py", line 6, in <module>                                       
    from .configuration import *
  File "/usr/lib/python3/dist-packages/trytond/modules/sale_pos_ar/configuration.py", line 9, in <module>                                  
    class Configuration(metaclass=PoolMeta):
  File "/usr/lib/python3/dist-packages/trytond/modules/sale_pos_ar/configuration.py", line 12, in Configuration                            
    pos = fields.Property(fields.Many2One('account.pos', 'Point of Sale'))                                                                 
AttributeError: module 'trytond.model.fields' has no attribute 'Property'
```
En la [documentación de tryton 4.2 figura en la parte de model fields](http://doc.tryton.org/projects/trytond/en/4.2/ref/models/fields.html#property), pero aparentemente [a partir de 4.4 no existe más](http://doc.tryton.org/projects/trytond/en/4.4/ref/models/fields.html).
Como si existe el [attribute Many2One](http://doc.tryton.org/projects/trytond/en/4.4/ref/models/fields.html#many2one) probé cambiar en [configuration.py de sale_pos_ar](https://github.com/tryton-ar/sale_pos_ar/blob/master/configuration.py#L13) por lo siguiente:
`pos = fields.Many2One('account.pos', 'Point of Sale')`
y ahí arranca tryton y puedo crear puntos de venta para la facturación (sólo probé facturación manual).

**Comment by lukio** [comment]
Hola @emondi, los campo property se reemplazaron por los MultiValue. sale_pos_ar todavía no se migro a la 4.4 (por ende, ni 4.6).

http://doc.tryton.org/projects/trytond/en/4.4/ref/models/fields.html#multivalue

**Comment by lukio** [comment]
Example how to remove property field and migrate it to multivalue. 
https://bugs.tryton.org/issue2349

**Comment by lukio** [comment]
commit: 76e51c60a7c0dd5033112f2d983f17ce3019c528 should fix the issue.
please test it and let me know.

**Comment by lukio** [comment]
@emondi, please test again. thanks!

**Comment by emondi** [comment]
Yes, it installs and starts now.
Sorry, got a power outage here.
